//
//  DeveloperPreview.swift
//  Airbnb
//
//  Created by admin on 02/01/2024.
//

import Foundation
class DeveloperPreview{
    static let shared = DeveloperPreview()
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Leonardo DiCaprio",
            ownerImageUrl: "owner4",
            numberOfBedrooms: 10,
            numberOfBathrooms: 8,
            numberOfGuests: 15,
            numberOfBeds: 8,
            pricePerNight: 1822,
            latitude: 20.959902,
            longitude: 107.042542,
            imageURLs: ["36","37","38","39","40","4","17","23","27","29"],
            address: "Ban Cat Cat St",
            city: "Sapa",
            state: "Lao Cai",
            title: "Beautiful Sapa apartment in Lao Cai",
            rating: 7.27,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .alarmSystem, .pool],
            type: .apartment
        ),
        
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "owner1",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 567,
            latitude: 25.7850,
            longitude: -80.1936,
            imageURLs: [ "1","2","3","4","5","6","7","8","9","10"],
            address: "124 Main St",
            city: "Los Angeles",
            state: "California",
            title: "Beautiful Los Angeles villa in California",

            rating: 4.86,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type:.villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Margot Robbie",
            ownerImageUrl: "owner2",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 763,
            latitude: 25.7650,
            longitude: -80.1938,
            imageURLs: [ "11","12","13","14","15","16","17","18","19","20"],
            address: "138 Street St",
            city: "Miami",
            state: "Florida",
            title: "Beautiful Miami apartment in downtown Florida",
            rating: 4.32,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .alarmSystem, .office, .pool],
            type:.apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Charlize Theron",
            ownerImageUrl: "owner3",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 763,
            latitude: 39.983334,
            longitude: -82.983330,
            imageURLs: [ "21","22","23","24","25","26","27","28","29","30"],
            address: "224 Second Main St",
            city: "Columbus",
            state: "Ohio",
            title: "Beautiful Columbus house in downtown Ohio",
            rating: 4.32,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .laundry, .balcony, .tv],
            type:.villa
        ),
        
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Leonardo DiCaprio",
                ownerImageUrl: "owner6",
                numberOfBedrooms: 5,
                numberOfBathrooms: 8,
                numberOfGuests: 10,
                numberOfBeds: 5,
                pricePerNight: 1522,
                latitude: 10.25516000,
                longitude: 104.01455000,
                imageURLs: ["56","57","58","59","60","44","47","53","55","16","47"],
                address: "Phu Quoc Street St",
                city: "Phu Quoc",
                state: "Kien Giang",
                title: "Beautiful Phu Quoc villa in Kien Giang",
                rating: 5.27,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .pool],
                type: .villa
            ),

        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Timothy Chalament",
            ownerImageUrl: "owner4",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 763,
            latitude: 34.1,
            longitude: -118.1426,
            imageURLs: ["5","6","7","8","9","10","11","12","13","14"],
            address: "4 Winny St",
            city: "Los Angeles",
            state: "California",
            title: "Beautiful Los Angeles house in Hollywood Hills",
            rating: 4.97,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .laundry, .pool, .alarmSystem],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jack Bauer",
            ownerImageUrl: "owner5",
            numberOfBedrooms: 5,
            numberOfBathrooms: 5,
            numberOfGuests: 7,
            numberOfBeds: 3,
            pricePerNight: 863,
            latitude: 40.730610,
            longitude: -73.935242,
            imageURLs: ["15","16","17","18","19","20","21","22","23","24"],
            address: "89 Downny St",
            city: "NewYork City",
            state: "NewYork",
            title: "Beautiful NewYork City apartment in NewYork",
            rating: 4.97,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .alarmSystem, .pool, .tv],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Kimi Raikkonen",
            ownerImageUrl: "owner6",
            numberOfBedrooms: 7,
            numberOfBathrooms: 8,
            numberOfGuests: 7,
            numberOfBeds: 4,
            pricePerNight: 763,
            latitude: 41.881832,
            longitude: -87.623177,
            imageURLs: ["3","4","5","6","7","8","9","10","1","12"],
            address: "422 Long Beach St",
            city: "Chicago",
            state: "LLinois",
            title: "Beautiful Chicago house in LLinois",
            rating: 4.27,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .kitchen, .pool, .balcony],
            type: .apartment
        ),
        
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Leonardo DiCaprio",
                ownerImageUrl: "owner7",
                numberOfBedrooms: 11,
                numberOfBathrooms: 5,
                numberOfGuests: 10,
                numberOfBeds: 6,
                pricePerNight: 1122,
                latitude: 21.028511,
                longitude: 105.804817,
                imageURLs: ["46","47","48","49","50","34","37","45","53","46"],
                address: "Lang Bac St",
                city: "Dong Da",
                state: "Ha Noi",
                title: "Beautiful Dong Da Tomb in Ha Noi",
                rating: 8.27,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .pool],
                type: .apartment
            ),
        
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Hugh Jackman",
            ownerImageUrl: "owner7",
            numberOfBedrooms: 7,
            numberOfBathrooms: 3,
            numberOfGuests: 5,
            numberOfBeds: 3,
            pricePerNight: 572,
            latitude: 29.749907,
            longitude: -95.358421,
            imageURLs: ["6","7","8","9","10","11","12","13","14","15"],
            address: "113 West Ham St",
            city: "Houston",
            state: "Texas",
            title: "Beautiful Houston apartment in Texas",
            rating: 5.17,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .office, .pool, .kitchen],
            type: .townHouse
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Robert Downey Jr",
            ownerImageUrl: "owner8",
            numberOfBedrooms: 5,
            numberOfBathrooms: 4,
            numberOfGuests: 6,
            numberOfBeds: 4,
            pricePerNight: 472,
            latitude: 30.266666,
            longitude: -97.733330,
            imageURLs: ["16","17","18","19","20","21","22","23","24","25"],
            address: "1454 Brighton St",
            city: "Austin",
            state: "Texas",
            title: "Beautiful Austin house in Texas",
            rating: 5.17,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .alarmSystem, .pool],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Johnny Depp",
            ownerImageUrl: "owner9",
            numberOfBedrooms: 4,
            numberOfBathrooms: 6,
            numberOfGuests: 8,
            numberOfBeds: 5,
            pricePerNight: 822,
            latitude: 42.361145,
            longitude: -71.057083,
            imageURLs: ["26","27","28","29","30","11","12","13","14","15"],
            address: "114 Manchester St",
            city: "Boston",
            state: "Massachusetts",
            title: "Beautiful Boston apartment in Massachusetts",
            rating: 6.77,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .alarmSystem, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jennifer Lawrence",
            ownerImageUrl: "owner1",
            numberOfBedrooms: 7,
            numberOfBathrooms: 4,
            numberOfGuests: 10,
            numberOfBeds: 6,
            pricePerNight: 1322,
            latitude: 47.751076,
            longitude: -120.740135,
            imageURLs: ["12","13","14","15","16","17","5","6","7","8"],
            address: "454 Liverpool St",
            city: "Washington",
            state: "D.C",
            title: "Beautiful Washington apartment in D.C",
            rating: 6.77,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .alarmSystem, .pool, .laundry],
            type: .townHouse
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Dwayne Johnson",
            ownerImageUrl: "owner2",
            numberOfBedrooms: 10,
            numberOfBathrooms: 8,
            numberOfGuests: 15,
            numberOfBeds: 8,
            pricePerNight: 1822,
            latitude: 39.742043,
            longitude: -104.991531,
            imageURLs: ["2","4","6","8","10","13","15","17","19","21"],
            address: "221 London St",
            city: "Denver",
            state: "Colorado",
            title: "Beautiful Denver apartment in Colorado",
            rating: 5.97,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .kitchen, .pool],
            type: .house
        ),
//        Next
        
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Scarlett Johansson",
                ownerImageUrl: "owner3",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 4,
                numberOfBeds: 4,
                pricePerNight: 567,
                latitude: 25.7850,
                longitude: -80.1936,
                imageURLs: [ "11","12","13","14","15","16","17","18","19","20"],
                address: "124 Main St",
                city: "Los Angeles",
                state: "California",
                title: "Beautiful Los Angeles apartment in California",

                rating: 4.86,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
                type:.villa
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Steve Johnson",
                ownerImageUrl: "owner4",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 4,
                numberOfBeds: 4,
                pricePerNight: 763,
                latitude: 25.7650,
                longitude: -80.1938,
                imageURLs: [ "7","5","2","4","13","6","17","22","27","30"],
                address: "138 Street St",
                city: "Miami",
                state: "Florida",
                title: "Beautiful Miami apartment in downtown Florida",
                rating: 7.32,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .balcony, .tv],
                type:.apartment
            ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Leonardo DiCaprio",
            ownerImageUrl: "owner7",
            numberOfBedrooms: 7,
            numberOfBathrooms: 7,
            numberOfGuests: 14,
            numberOfBeds: 5,
            pricePerNight: 1522,
            latitude: 15.87944000,
            longitude: 108.33500000,
            imageURLs: ["51","52","53","54","55","24","37","43","45","46"],
            address: "Hoi An Street St",
            city: "Hoi An",
            state: "Quang Nam",
            title: "Beautiful Hoi An village in Quang Nam",
            rating: 5.27,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .alarmSystem, .pool],
            type: .apartment
        ),
   
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Tom Hiddleston",
                ownerImageUrl: "owner5",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 4,
                numberOfBeds: 4,
                pricePerNight: 763,
                latitude: 39.983334,
                longitude: -82.983330,
                imageURLs: [ "15","12","13","14","29","30","7","8","3","2"],
                address: "224 Second Main St",
                city: "Columbus",
                state: "Ohio",
                title: "Beautiful Columbus house in downtown Ohio",
                rating: 7.32,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .balcony, .laundry],
                type:.townHouse
            ),
            
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Cate Blanchett",
                ownerImageUrl: "owner6",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 4,
                numberOfBeds: 4,
                pricePerNight: 763,
                latitude: 34.1,
                longitude: -118.1426,
                imageURLs: ["7","2","1","18","19","20","19","21","23","24"],
                address: "4 Winny St",
                city: "Los Angeles",
                state: "California",
                title: "Beautiful Los Angeles home in Hollywood Hills",
                rating: 6.97,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .laundry, .tv],
                type: .house
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Ryan Reynolds",
                ownerImageUrl: "owner7",
                numberOfBedrooms: 5,
                numberOfBathrooms: 5,
                numberOfGuests: 7,
                numberOfBeds: 3,
                pricePerNight: 863,
                latitude: 40.730610,
                longitude: -73.935242,
                imageURLs: ["5","6","17","8","2","15","24","25","30","12"],
                address: "89 Downny St",
                city: "NewYork City",
                state: "NewYork",
                title: "Beautiful NewYork City apartment in NewYork",
                rating: 4.97,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .balcony, .laundry, .tv],
                type: .villa
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Emilia Clarke",
                ownerImageUrl: "owner8",
                numberOfBedrooms: 7,
                numberOfBathrooms: 8,
                numberOfGuests: 7,
                numberOfBeds: 4,
                pricePerNight: 763,
                latitude: 41.881832,
                longitude: -87.623177,
                imageURLs: ["13","14","15","16","27","18","19","20","21","14"],
                address: "422 Long Beach St",
                city: "Chicago",
                state: "LLinois",
                title: "Beautiful Chicago house in LLinois",
                rating: 4.27,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .pool],
                type: .apartment
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Taron Egerton",
                ownerImageUrl: "owner9",
                numberOfBedrooms: 7,
                numberOfBathrooms: 3,
                numberOfGuests: 5,
                numberOfBeds: 3,
                pricePerNight: 572,
                latitude: 29.749907,
                longitude: -95.358421,
                imageURLs: ["16","30","81","19","20","1","13","14","15","16"],
                address: "113 West Ham St",
                city: "Houston",
                state: "Texas",
                title: "Beautiful Houston apartment in Texas",
                rating: 6.17,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .pool],
                type: .villa
            ),
          .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Leonardo DiCaprio",
            ownerImageUrl: "owner8",
            numberOfBedrooms: 10,
            numberOfBathrooms: 8,
            numberOfGuests: 15,
            numberOfBeds: 8,
            pricePerNight: 1822,
            latitude: 20.959902,
            longitude: 107.042542,
            imageURLs: ["31","32","33","34","35","4","7","13","5","6"],
            address: "143 Van Don St",
            city: "Ha Long",
            state: "Quang Ninh",
            title: "Beautiful Ha Long villa in Quang Ninh",
            rating: 5.27,
            features: [.selfCheckIn,.superHost],
            amenities: [.wifi, .alarmSystem, .pool],
            type: .villa
        ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Ma Dong Seok",
                ownerImageUrl: "owner4",
                numberOfBedrooms: 5,
                numberOfBathrooms: 4,
                numberOfGuests: 6,
                numberOfBeds: 4,
                pricePerNight: 472,
                latitude: 30.266666,
                longitude: -97.733330,
                imageURLs: ["12","6","8","9","21","24","12","3","4","5"],
                address: "1454 Brighton St",
                city: "Austin",
                state: "Texas",
                title: "Beautiful Austin house in Texas",
                rating: 5.17,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .pool],
                type: .townHouse
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Jared Leto",
                ownerImageUrl: "owner2",
                numberOfBedrooms: 4,
                numberOfBathrooms: 6,
                numberOfGuests: 8,
                numberOfBeds: 5,
                pricePerNight: 822,
                latitude: 42.361145,
                longitude: -71.057083,
                imageURLs: ["16","7","8","9","3","12","14","11","16","18"],
                address: "114 Manchester St",
                city: "Boston",
                state: "Massachusetts",
                title: "Beautiful Boston apartment in Massachusetts",
                rating: 5.77,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .pool],
                type: .apartment
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Vin Diesel",
                ownerImageUrl: "owner6",
                numberOfBedrooms: 7,
                numberOfBathrooms: 4,
                numberOfGuests: 10,
                numberOfBeds: 6,
                pricePerNight: 1322,
                latitude: 47.751076,
                longitude: -120.740135,
                imageURLs: ["2","13","11","7","16","8","15","14","17","3"],
                address: "454 Liverpool St",
                city: "Washington",
                state: "D.C",
                title: "Beautiful Washington apartment in D.C",
                rating: 7.47,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .pool],
                type: .house
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Leonardo DiCaprio",
                ownerImageUrl: "owner8",
                numberOfBedrooms: 10,
                numberOfBathrooms: 8,
                numberOfGuests: 15,
                numberOfBeds: 8,
                pricePerNight: 1822,
                latitude: 39.742043,
                longitude: -104.991531,
                imageURLs: ["12","14","3","4","5","11","12","13","9","26"],
                address: "221 London St",
                city: "Denver",
                state: "Colorado",
                title: "Beautiful Denver apartment in Colorado",
                rating: 5.27,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .pool],
                type: .apartment
            ),
      
     
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Leonardo DiCaprio",
                ownerImageUrl: "owner2",
                numberOfBedrooms: 10,
                numberOfBathrooms: 8,
                numberOfGuests: 15,
                numberOfBeds: 8,
                pricePerNight: 1822,
                latitude: 20.25061490,
                longitude: 105.97445360,
                imageURLs: ["41","42","43","44","45","4","36","37","35","26"],
                address: "Tam Coc Bich Dong St",
                city: "Trang An",
                state: "Ninh Binh",
                title: "Beautiful Trang An zoo in Ninh Binh",
                rating: 8.27,
                features: [.selfCheckIn,.superHost],
                amenities: [.wifi, .alarmSystem, .pool],
                type: .apartment
            ),
       
        


        
    ]
}
